# Generated by Django 4.2.2 on 2025-03-27 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_reset_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_view_all_users", "Can view all users"),
                    ("can_block_users", "Can block users"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
