# Generated by Django 4.2.2 on 2025-03-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatcher", "0003_mailing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("1", "Создана"),
                    ("2", "Активна"),
                    ("3", "Завершена"),
                ],
                default="1",
                max_length=6,
                verbose_name="Статус",
            ),
        ),
    ]
