# Generated by Django 4.2.2 on 2025-03-22 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dispatcher", "0004_alter_mailing_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="date_time_end_mailing",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Дата и время окончания отправки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="date_time_of_first_mailing",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Дата и время первой отправки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mailings",
                to="dispatcher.message",
                verbose_name="Сообщение",
            ),
        ),
    ]
