# Generated by Django 4.2.2 on 2025-03-22 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0005_alter_mailing_date_time_end_mailing_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelTable(
            name='mailing',
            table='Рассылки',
        ),
    ]
