# Generated by Django 4.2.2 on 2025-03-22 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dispatcher", "0006_alter_mailing_options_alter_mailing_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelTable(
            name="message",
            table="Сообщения",
        ),
    ]
