# Generated by Django 4.2.2 on 2025-03-23 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dispatcher", "0008_alter_mailing_date_time_end_mailing"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttemptToMailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_time_of_attempt",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата и время попытки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("1", "Успешно"), ("0", "Не успешно")],
                        max_length=6,
                        null=True,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "mail_server_response",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Ответ почтового сервера",
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attempts",
                        to="dispatcher.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
        ),
    ]
