# Generated by Django 4.2.2 on 2025-03-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatcher", "0010_attempttomailing_sent_messages_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attempttomailing",
            name="sent_messages_count",
        ),
        migrations.AddField(
            model_name="attempttomailing",
            name="messages_count",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True
            ),
        ),
    ]
